apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
spec:
  ingressClassName: alb
  tls:
    - hosts:
      - {{ index .Values "argo-cd" "global" "domain" }}
  rules:
  - host: {{ index .Values "argo-cd" "global" "domain" }}
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 443
        path: /
        pathType: Prefix
